//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStoresData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProduct
    {
        public int SPID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
